### ISSUE TITLE
Multiple uses in same process?

### ISSUE THREAD

**Issue by Efreak** [cpancake/steam-login#3]
I'm using steam-login for [my steam bot](https://github.com/Steam-Chat-Bot/node-steam-chat-bot/blob/development/lib/triggers/webUI.js). Basically each express instance listens on a different port number on the same IP address, and I connect to them via Nginx reverse proxy setup for subdomains. This is generally working the way it should for a single instance under a single process, except that I'm running multiple bots under the same process; when I do so, all logins are being redirected according to the last steam-login instance created.

In other words, I set up the following bots, and add steam-login to them in order, with the given urls:
1. miley.efreakbnc.net/api/login
2. sgs.efreakbnc.net/api/login
3. trivia.efreakbnc.net/api/login

However, when I visit any one of these pages, it attempts to log me in--but the return uri is set to the last one (if I omit the trivia one, logging into miley sends me to sgs).

Is there anything I can do to fix this? When I visit miley.efreakbnc.net/api/login, I'd like to have it redirect me to miley.efreakbnc.net/api/verify instead of trivia.efreakbnc.net/api/verify.

**Comment by dialupnoises** [comment]
There isn't a way to do it with the code currently, since it uses a few global variables for storing configuration. This was a bad idea on my part, but I wasn't setting out to make the most complete Steam login implementation - just one that was easy to use. 

However, you should be able to use passport-steam to be able to do this.
